- name: check password requirements
  shell:
    "cat /etc/pam.d/password-auth | awk '/remember/' "
  register: out
- set_fact:
    password_requirements_pam : "{{ out.stdout_lines }}"
- debug:
   var: password_requirements_pam
- local_action: lineinfile line='{{ inventory_hostname }}	{{ password_requirements_pam }}' path=/tmp/output.json

- name: check password requirements
  shell:
    "cat /etc/security/pwquality.conf | awk '/minlen/||/minclass/||/dcredit/||/ucredit/||/ocredit/||/lcredit/' "
  register: out
- set_fact:
    password_requirements_security : "{{ out.stdout_lines }}"
- debug:
   var: password_requirements_security
- local_action: lineinfile line='{{ inventory_hostname }}	{{ password_requirements_security }}' path=/tmp/output.json

- name: check password requirements
  shell:
    "cat /etc/pam.d/password-auth | awk '/remember/' "
  register: out
- set_fact:
    password_reuse_limited : "{{ out }}"
- debug:
   var: password_reuse_limited
- local_action: lineinfile line='{{ inventory_hostname }}	{{ password_reuse_limited }}' path=/tmp/output.json

- name: check password requirements
  shell:
    "cat /etc/pam.d/password-auth | awk '/sha512/' "
  register: out
- set_fact:
    password_hash : "{{ out.stdout_lines }}"
- debug:
   var: password_hash
- local_action: lineinfile line='{{ inventory_hostname }}	{{ password_hash }}' path=/tmp/output.json

- name: check password requirements
  shell:
    "cat /etc/pam.d/system-auth | awk '/remember/' "
  register: out
- set_fact:
    system_password_reuse_limited : "{{ out.stdout_lines }}"
- debug:
   var: system_password_reuse_limited
- local_action: lineinfile line='{{ inventory_hostname }}	{{ system_password_reuse_limited }}' path=/tmp/output.json

- name: check password requirements
  shell:
    "cat /etc/pam.d/system-auth | awk '/sha512/' "
  register: out
- set_fact:
    system_password_hash : "{{ out.stdout_lines }}"
- debug:
   var: system_password_hash
- local_action: lineinfile line='{{ inventory_hostname }}	{{ system_password_hash }}' path=/tmp/output.json

- name: check password expiration
  shell:
    "cat /etc/login.defs | awk '/PASS_MAX_DAYS/{print $2}'"
  register: out
- set_fact:
    PASS_MAX_DAYS : "{{ out.stdout_lines.1 }}"
- debug:
   var: PASS_MAX_DAYS
- local_action: lineinfile line='{{ inventory_hostname }}	PASS_MAX_DAYS:{{ PASS_MAX_DAYS }}' path=/tmp/output.json

- name: check users password expiration
  shell:
    "grep -E '^[^:]+:[^!*]' /etc/shadow | cut -d: -f1,5"
  register: out
- set_fact:
    USER_PASS_MAX_DAYS : "{{ out.stdout }}"
- debug:
   var: USER_PASS_MAX_DAYS
- local_action: lineinfile line='{{ inventory_hostname }}	USER_PASS_MAX_DAYS:{{ USER_PASS_MAX_DAYS }}' path=/tmp/output.json

- name: check password minimum days before changing
  shell:
    "cat /etc/login.defs | awk '/PASS_MIN_DAYS/{print $2}'"
  register: out
- set_fact:
    PASS_MIN_DAYS : "{{ out.stdout_lines.1 }}"
- debug:
   var: PASS_MIN_DAYS
- local_action: lineinfile line='{{ inventory_hostname }}	PASS_MIN_DAYS:{{ PASS_MIN_DAYS }}' path=/tmp/output.json

- name: check users password minimum days before changing
  shell:
    "grep -E '^[^:]+:[^!*]' /etc/shadow | cut -d: -f1,4"
  register: out
- set_fact:
    USER_PASS_MIN_DAYS : "{{ out.stdout }}"
- debug:
   var: USER_PASS_MIN_DAYS
- local_action: lineinfile line='{{ inventory_hostname }}	USER_PASS_MIN_DAYS:{{ USER_PASS_MIN_DAYS }}' path=/tmp/output.json

- name: check password expiration warning days
  shell:
    "cat /etc/login.defs | awk '/PASS_WARN_AGE/{print $2}'"
  register: out
- set_fact:
    PASS_WARN_AGE : "{{ out.stdout_lines.1 }}"
- debug:
   var: PASS_WARN_AGE
- local_action: lineinfile line='{{ inventory_hostname }}	PASS_WARN_AGE:{{ PASS_WARN_AGE }}' path=/tmp/output.json

- name: check password expiration warning days
  shell:
    "grep -E '^[^:]+:[^!*]' /etc/shadow | cut -d: -f1,6"
  register: out
- set_fact:
    USER_PASS_WARN_AGE : "{{ out.stdout }}"
- debug:
   var: USER_PASS_WARN_AGE
- local_action: lineinfile line='{{ inventory_hostname }}	USER_PASS_WARN_AGE:{{ USER_PASS_WARN_AGE }}' path=/tmp/output.json
